# Generated by Django 4.2.30 on 2026-07-07 06:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_update_unified_shop_view_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('token_type', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HandoverConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('handed_over_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'handover_confirmations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HarvestSheetView',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('sale_session_id', models.UUIDField()),
                ('pickup_point_id', models.UUIDField()),
                ('producer_id', models.UUIDField()),
                ('farm_name', models.CharField(max_length=150)),
                ('product_id', models.UUIDField()),
                ('product_name', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=30)),
                ('total_quantity_to_prepare', models.DecimalField(decimal_places=3, max_digits=12)),
                ('order_count', models.IntegerField()),
            ],
            options={
                'db_table': 'harvest_sheet_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_code', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_submitted', 'Payment Submitted'), ('confirmed', 'Confirmed'), ('ready', 'Ready'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('mvola', 'Mvola'), ('orange_money', 'Orange Money'), ('airtel_money', 'Airtel Money'), ('stripe', 'Stripe (Carte bancaire)')], max_length=20)),
                ('proof_file_path', models.TextField()),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('distribution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pickup_points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=150)),
                ('location', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'producers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_path', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('available_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('is_promoted', models.BooleanField(db_column='is_promoted', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_stocks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaleSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('pickup_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('distributed', 'Distributed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sale_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnifiedShopView',
            fields=[
                ('product_id', models.UUIDField(primary_key=True, serialize=False)),
                ('sale_session_id', models.UUIDField()),
                ('pickup_point_id', models.UUIDField()),
                ('pickup_point_name', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=150)),
                ('product_description', models.TextField()),
                ('unit', models.CharField(max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_image_path', models.TextField(blank=True, null=True)),
                ('category_name', models.CharField(max_length=100)),
                ('producer_id', models.UUIDField()),
                ('farm_name', models.CharField(max_length=150)),
                ('available_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reserved_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('remaining_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('opens_at', models.DateTimeField()),
                ('closes_at', models.DateTimeField()),
                ('pickup_date', models.DateField()),
                ('sale_session_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'unified_shop_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(blank=True, max_length=180, null=True, unique=True)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('consumer', 'Consumer'), ('producer', 'Producer'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProducerPickupPoint',
            fields=[
                ('producer', models.OneToOneField(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.producer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'producer_pickup_points',
                'managed': False,
            },
        ),
    ]
