/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'inverse-primary': '#8bd79b',
        'surface-container-highest': '#d5e3fd',
        'primary-fixed': '#a6f4b5',
        'surface-container': '#e6eeff',
        background: '#fafaf9',
        'on-tertiary-container': '#ffc47d',
        'surface-tint': '#1f6c3a',
        tertiary: '#5d3900',
        'on-error': '#ffffff',
        error: '#ba1a1a',
        primary: '#004c22',
        'secondary-container': '#fb7b54',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#233144',
        'surface-container-low': '#eff4ff',
        'secondary-fixed': '#ffdbd1',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#842503',
        'tertiary-fixed-dim': '#ffb95f',
        'tertiary-fixed': '#ffddb8',
        'primary-fixed-dim': '#8bd79b',
        'on-surface': '#0d1c2f',
        'on-secondary-container': '#6b1a00',
        'on-secondary-fixed': '#3a0a00',
        'inverse-on-surface': '#ebf1ff',
        'on-primary-fixed-variant': '#005226',
        'outline-variant': '#bfc9bd',
        'tertiary-container': '#7d4e00',
        surface: '#f8f9ff',
        outline: '#707a6f',
        'surface-bright': '#f8f9ff',
        'on-primary-container': '#93e0a2',
        'primary-container': '#166534',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#653e00',
        'on-secondary': '#ffffff',
        secondary: '#a53c19',
        'on-tertiary-fixed': '#2a1700',
        'on-primary-fixed': '#00210b',
        'secondary-fixed-dim': '#ffb59f',
        'on-primary': '#ffffff',
        'on-surface-variant': '#404940',
        'surface-container-high': '#dde9ff',
        'on-background': '#0d1c2f',
        'surface-variant': '#d5e3fd',
        'surface-dim': '#ccdbf4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '32px',
        lg: '24px',
        base: '4px',
        xs: '4px',
        xl: '40px',
        'margin-mobile': '16px',
        gutter: '16px',
        sm: '8px',
        md: '16px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Public Sans', 'sans-serif'],
        'headline-lg': ['Public Sans', 'sans-serif'],
        'label-md': ['Public Sans', 'sans-serif'],
        'body-md': ['Public Sans', 'sans-serif'],
        'headline-md': ['Public Sans', 'sans-serif'],
        'label-sm': ['Public Sans', 'sans-serif'],
        'body-lg': ['Public Sans', 'sans-serif'],
        sans: ['Public Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
